opencv_legacy
opencv_haartraining_engine
opencv_calib3d 
opencv_features2d
opencv_objdetect 
opencv_imgproc
opencv_video  
opencv_highgui 
opencv_ml 
opencv_legacy 
opencv_core 
opencv_flann
opencv_contrib
opencv_gpu
