language: c++
sudo: required
compiler: gcc
#cache: 
#    - ccache
#    - apt
env:
  matrix:
    - NAME="linux" \
        OF_ROOT="$PWD" \
        SCRIPT="scripts/linux/testTemplate.sh"
before_install: 
    - sudo scripts/linux/ubuntu/install_dependencies.sh
    - export CXX=g++-4.9
script:
    $SCRIPT
git:
    depth: 1
notifications:
    webhooks: http://192.237.185.151/web-hooks/travis_done.cgi
