################################################################################
# OPENFRAMEWORKS MAKEFILE
#   The openFrameworks makefile system is designed for ease of use, and 
#   particularly for straight-forward platform-based configurations.
#
#   Read the documentation or simply execute :
#
#   make help 
#
#   for a brief help file.
#
################################################################################

# define the OF_SHARED_MAKEFILES location
OF_SHARED_MAKEFILES_PATH=./makefileCommon


# include the global configuration file
include $(OF_SHARED_MAKEFILES_PATH)/config.shared.mk
include $(OF_SHARED_MAKEFILES_PATH)/compile.core.mk

