opencv_legacy 
opencv_calib3d
opencv_features2d 
opencv_haartraining_engine
opencv_objdetect 
opencv_imgproc
opencv_video  
opencv_highgui 
opencv_ml 
opencv_core 
opencv_lapack 
opencv_flann
opencv_contrib
zlib 
