CC=gcc
CFLAGS=-I./include

LIB=libkiss.a
LIBDEST=./lib/linuxarmv6l/

LIBSRC=src/kiss_fft.c src/kiss_fftr.c 

LIBOBJ=$(LIBSRC:.c=.o)

install: $(LIB)
	@echo lib Makefile - installing $(LIB)
	@install -m 444 $(LIB) $(LIBDEST)

$(LIB): $(LIBOBJ)
	@echo lib Makefile - archiving $(LIB)
	@$(AR) r $(LIB) $(LIBOBJ)

.c.o:
	@echo lib Makefile - compiling $<
	@$(CC) $(CFLAGS) -c $< -o $@


