name: build-rpi

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ccache: ccache

jobs:
  rpi-build:
    runs-on: ubuntu-24.04
    strategy:
        matrix:
          cfg:
          - { libs: armv6l, multistrap_arch: armhf, suffix: arm-linux-gnueabihf, alladdons: 1 }
          - { libs: aarch64,  multistrap_arch: arm64, suffix: aarch64-linux-gnu, alladdons: 1 }
    env:
     ARCH: ${{matrix.cfg.libs}}
     MULTISTRAP_ARCH: ${{matrix.cfg.multistrap_arch}}
     ALLADDONSEXAMPLE: ${{matrix.cfg.alladdons}}
    steps:
    - name: Cache Packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: wget2 multistrap unzip gcc-${{matrix.cfg.suffix}} g++-${{matrix.cfg.suffix}}
        version: 1.0

    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.14
      with:
        key: ${{ matrix.cfg.libs }}

    - name: Download libs
      run: ./scripts/linux/download_libs.sh -a ${{matrix.cfg.libs}};
    - name: Install dependencies
      run: ./scripts/ci/linuxrpi/install.sh;
    - name: Build
      run: ./scripts/ci/linuxrpi/build.sh;
