libopencv_legacy.a 
libopencv_calib3d.a
libopencv_features2d.a 
libopencv_objdetect.a 
libopencv_imgproc.a
libopencv_video.a  
libopencv_highgui.a 
libopencv_ml.a 
libopencv_core.a 
libopencv_flann.a
libopencv_contrib.a
