name: build-ios-tvos

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
    
jobs:
  build-osx:
    runs-on: macos-12
    strategy:
        matrix:
          cfg:
          - {target: ios, libs: ios}
          #- {target: tvos, libs: ios} #broken currently maybe better to just remove
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - name: Download libs
      run: ./scripts/${{matrix.cfg.libs}}/download_libs.sh
    - name: install
      run: ./scripts/ci/$TARGET/install.sh
    - name: Build
      run: ./scripts/ci/$TARGET/build.sh;

      env:
        DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"
