#! /bin/bash
#
# this is the OpenFrameworks library apothecary,
# it mixes formulas and potions to build and update the C/C++ lib dependencies
#
# 2013 Dan Wilcox <danomatika@gmail.com>
#
# references:
#  http://stackoverflow.com/questions/12219001/standalone-shell-script-vs-shell-function
#  http://www.tldp.org/LDP/abs/html/comparison-ops.html
#  http://tldp.org/LDP/abs/html/fto.html
#  http://www.developer.com/open/article.php/631241/Linux-Console-Colors--Other-Tricks.htm
#  http://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash
#  http://stackoverflow.com/questions/64786/error-handling-in-bash
#  http://www.linuxjournal.com/content/bash-arrays

################################################################################
### GLOBAL VARS, for access inside formulas

### SET IN FORMULA script

# an array of build type strings supported by the forumla (optional)
# see VALID_TYPES for list of strings, default: VALID_TYPES
FORMULA_TYPES=

### READ ONLY please!

# build settings
OS= # compile os ("osx", "windows", "linux")
TYPE= # library build type ("osx", "ios", "vs2010", etc)
ARCH=32 # library build arch, 32 or 64 bit (not used for some build types)

# full path to this script's dir
APOTHECARY_DIR=.

# full path to the dir of the current formula
FORMULA_DIR=

# full path to the download/build dir
BUILD_DIR=

### Xcode/ios specific settings

# xcode Developer root
XS="xcode-select -print-path" # stupid hack to keep my syntax highlighting from breaking :P
XCODE_DEV_ROOT=$($XS)

# used when building some libs for osx
OSX_SDK_VER=10.8
OSX_MIN_SDK_VER=10.6

# used when building for ios, the sdks you have installed are found in:
# $XCODE_DEV_ROOT/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator#.#.sdk
IOS_SDK_VER=6.1
IOS_MIN_SDK_VER=5.1

################################################################################
### PRIVATE VARS, for internal use
### DEFINITELY READ ONLY!

# destination dir for compiled libs
A_LIBS_DIR=.. # default: relative to script

# paths relative to this script
REL_FORMULAS_DIR=formulas
REL_BUILD_DIR=build

# ansi console escape codes
CON_DEFAULT="\033[0m"
CON_BOLD="\033[1m"
CON_RED="\033[31m"
CON_YELLOW="\033[93m"
CON_GREEN="\033[32m"

# used to filter out bad build types
VALID_TYPES=( "osx" "linux" "linux64" "vs2010" "win_cb" "ios" "android" )

# verbose mode bool
A_VERBOSE=0

# nice, detailed help message
HELP="Usage: apothecary [options] command [libraries]

 this is the OpenFrameworks library apothecary
 it mixes formulas and potions to build and update OF C/C++ lib dependencies

 Commands:
  update		download, build, and copy library files
  clean 		clean the build cache
  dist-clean		clean the build cache and lib folder

 Options:
  -t	specify libary type when building, detects type from OS by default
	valid types: osx, linux, linux64, vs2010, win_cb, ios, android

  -a	specify architecture, either 32 or 64 (default is 32 bit)
	note: currently only applies to linux build types (linux & linux64)

  -b 	set the lib build dir, default: \$APOTHECARY_DIR/build

  -d 	set the compiled libs destination dir, default: OF core libs dir

  -v 	verbose mode, print out some extra info while mixing formulas

  -h    print this usage guide

 Examples:

  # update all libs in the formulas dir
  apothecary update

  # update only glew
  apothecary update glew
 
  # clean all downloaded lib src dirs in the cache
  apothecary clean

  # clean only assimp & glew in the cache
  apothecary clean assimp glew

  # clean glew from the cache and lib folder
  apothecary dist-clean glew

  # update freetype for ios 
  apothecary -t ios freetype

  # update assimp for 64bit OSX (maybe in the future ...)
  apothecary -t osx -a 64 assimp
"

################################################################################
#### SET ERROR HANDLING

#set -x # run script in debug mode

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   # set -u : exit the script if you try to use an uninitialized variable
set -o errexit   # set -e : exit the script if any statement returns a non-true return value

# trap the killer signals so that we can exit with a good message
trap "trapSignal SIGHUP" SIGHUP
trap "trapSignal SIGINT" SIGINT
trap "trapSignal SIGTERM" SIGTERM

trapSignal() {
	echo
	echoError " Received signal $1"
	exit 1
}

# trap any script errors and exit
trap "trapError" ERR

trapError() {
	echo
	echoError " ^ Received error ^"
	exit 1
}

# console printing functions (with color)
echoError()		{
	echo -e "$CON_BOLD$CON_RED$1$CON_DEFAULT"
}
echoWarning()	{
	echo -e "$CON_BOLD$CON_YELLOW$1$CON_DEFAULT"
}
echoInfo()		{
	echo -e "$CON_BOLD$1$CON_DEFAULT"
}
echoSuccess()	{
	echo -e "$CON_BOLD$CON_GREEN$1$CON_DEFAULT"
}
echoVerbose() {
	if [ $A_VERBOSE == 1 ] ; then
		echoInfo "$1"
	fi
}

################################################################################
#### PARSE COMMANDLINE

# from http://www.mkssoftware.com/docs/man1/getopts.1.asp
while getopts t:a:b:d:vh opt ; do
	case "$opt" in
		t) # set the library build type
		   TYPE="$OPTARG" ;;
		a) # set the architecture
		   ARCH=$OPTARG ;;
		b) # set the build dir
		   BUILD_DIR="$OPTARG" ;;
		d) # set lib destination dir
		   A_LIBS_DIR="$OPTARG" ;;
		h) # print help and exit
		   echo "$HELP" ; exit 0 ;;
		v) # verbose mode = true
		   A_VERBOSE=1 ;;
		[?]) # print help and exit 
			 echo "$HELP" ; exit 0 ;;
	esac
done
shift $(expr $OPTIND - 1)

# get command
if [ "$1" != "" ] ; then
	A_CMD=$1
else
	echo "$HELP"
	exit 0
fi
shift 1

################################################################################
### FUNCTIONS

# check if a given string matches anything in VALID_TYPES,
# bool result is set to second argument
function isValidType() {
	local i
	for i in "${VALID_TYPES[@]}" ; do
		if [ "$i" == "$1" ] ; then
			eval $2=1
			return
		fi
	done
	eval $2=0
}

# check if a given string matches anything in FORMULA_TYPES,
# bool result is set to second argument 
function isFormulaType() {
	local i
	for i in "${FORMULA_TYPES[@]}" ; do
		if [ "$i" == "$1" ] ; then
			eval $2=1
			return
		fi
	done
	eval $2=0
}

# update a given library
function update() {

	local formula=$REL_FORMULAS_DIR/$1.sh
	FORMULA_DIR=$APOTHECARY_DIR/$REL_FORMULAS_DIR

	# is given formula an existing script?
	if [ -e $1 -a "${1##*.}" == "sh" ] ; then
		local path=$1	
		case $1 in
			/*) : ;; # absolute path
			 *) path=$WD/$1 ;; # relative path
		esac
		formula=$path
		FORMULA_DIR=$(dirname $path)
	
	else # formula in formula's dir
	
		# check if the given lib name is even formula
		if [ ! -e $formula ] ; then
			
			# is the given formula a dir?
			if [ -e $REL_FORMULAS_DIR/$1 -a -d $REL_FORMULAS_DIR/$1 ] ; then
				formula=$REL_FORMULAS_DIR/$1/$1.sh
				FORMULA_DIR=$APOTHECARY_DIR/$REL_FORMULAS_DIR/$1
			else
				echoError " No formula for lib \"$1\""
				exit 1
			fi
		fi
	fi

	# load a script & it's function implementations
	source $formula
	formula=$(basename $formula)
	local currentLib="${formula%.*}"

	# does this formula support the current build type?
	local bFormulaType=0 # bool
	isFormulaType $TYPE bFormulaType
	if [ $bFormulaType == 0 ] ; then
		echoInfo " Skipping \"$currentLib\": build not needed for type \"$TYPE\""
		FORMULA_TYPES=("${VALID_TYPES[@]}") # copy array
		return
	fi

	### DOWNLOAD

	# download src to cache
	echo
	echoInfo " ----- $currentLib -----"
	echoVerbose " Formula dir: $FORMULA_DIR"
	echoVerbose " Formula build types: ${FORMULA_TYPES[*]}"
	echoInfo " Downloading \"$currentLib\""
	echo

	mkdir -p $BUILD_DIR
	cd $BUILD_DIR

	if [ -e $currentLib ] ; then
		echo "... skipping, src dir already exists"

	else
		download
		cd $BUILD_DIR
		if [ ! -e $currentLib ] ; then
			echoError " It looks like downloading failed for \"$currentLib\""
			exit 1
		fi
	fi

	### BUILD

	# run build command in src dir
	echo
	echoInfo " Building \"$currentLib\""
	echo

	cd $currentLib
	build
	cd $BUILD_DIR/$currentLib

	### COPY

	# dest arg path relative to src dir
	echo
	echoInfo " Copying \"$currentLib\""
	echo

	case $A_LIBS_DIR in
		/*) copy $A_LIBS_DIR/$currentLib ;; # absolute path
		 *) copy $APOTHECARY_DIR/$A_LIBS_DIR/$currentLib ;; # relative path
	esac
	cd $APOTHECARY_DIR

	echo
	echoSuccess " Finished \"$currentLib\""

	### CLEANUP

	# reset to all types
	FORMULA_TYPES=("${VALID_TYPES[@]}") # copy array
}

# clean a given library from the cache
function clean() {

	# check if the given lib name is even a formula
	if [ ! -e $REL_FORMULAS_DIR/$1.sh -a ! -e $REL_FORMULAS_DIR/$1 ] ; then
		echoError " No formula for lib \"$1\""
		exit 1
	fi

	cd $REL_BUILD_DIR
	rm -rf $1*
	echoSuccess " Cleaned \"$1\" from build cache"
	cd $APOTHECARY_DIR
}

# clean a given library from the cache and lib folder
function dist-clean() {

	# check if the given lib name is even a formula
	if [ ! -e $REL_FORMULAS_DIR/$1.sh -a ! -e $REL_FORMULAS_DIR/$1 ] ; then
		echoError " No formula for lib \"$1\""
		exit 1
	fi

	cd $BUILD_DIR
	rm -rf $1*
	echoSuccess " Cleaned \"$1\" from build cache"
	cd $APOTHECARY_DIR

	cd $A_LIBS_DIR
	rm -rf $1
	echoSuccess " Cleaned \"$1\" from libs folder"
	cd $APOTHECARY_DIR
}

################################################################################
### GO

# record current working dir
WD=$(pwd)

# change to the dir of this script
cd $(dirname $0)
APOTHECARY_DIR=$(pwd)

# set OS & build types
OS=`./ostype.sh`
if [ "$TYPE" == "" ] ; then
	case "$OS" in
		windows)
			TYPE="vs2010" ;;
		*)
			TYPE=$OS ;;
	esac
fi
FORMULA_TYPES=("${VALID_TYPES[@]}") # copy array
echoVerbose "Valid build types: ${VALID_TYPES[*]}"


# check if we have a valid build type
typeIsValid=0 # bool
isValidType $TYPE typeIsValid
if [ $typeIsValid == 0 ] ; then
	echoError " Invalid build type: \"$TYPE\""
	exit 1
fi
echoVerbose "Build type: $TYPE"

# check if we have a valid arch
if [ $ARCH != 32 -a $ARCH != 64 ] ; then
	echoError " Invalid architecture: $ARCH"
	exit 1
fi
echoVerbose "Architecture: $ARCH"

# use default build dir?
if [ "$BUILD_DIR" == "" ] ; then
	BUILD_DIR=$APOTHECARY_DIR/$REL_BUILD_DIR
else # manually set

	# check build location
	if [ ! -e $BUILD_DIR ] ; then
		echoError " Invalid build dir: \"$BUILD_DIR\""
		exit 1
	fi

	case $BUILD_DIR in
		/*) : ;; # absolute path
	 	*) BUILD_DIR=$WD/$BUILD_DIR ;; # relative path
	esac
fi
echoVerbose "Build dir: $BUILD_DIR"

# check libs location
if [ ! -e $A_LIBS_DIR ] ; then
	echoError " Invalid libs dir: \"$A_LIBS_DIR\""
	exit 1
fi
echoVerbose "Libs destination dir: $A_LIBS_DIR"

# handle commands
echoVerbose "Running: $A_CMD $@"
case "$A_CMD" in

	update)
		# process given libraries
		if [ $# -gt 0 ] ; then
			while [ $# -gt 0 ] ; do
				update $1
				shift 1
			done

		else # process all formulas
			for formula in $( ls -1 $REL_FORMULAS_DIR) ; do
				#if [ ! -d $formula ] ; then # ignore directories 
					update "${formula%.*}" # removes file extension
				#fi
			done
		fi ;;

	clean)

		if [ ! -e $BUILD_DIR ] ; then
			echoInfo " Nothing to clean"
			exit 0
		fi

		# process given libraries
		if [ $# -gt 0 ] ; then
			while [ $# -gt 0 ] ; do
				clean $1
				shift 1
			done

		else # process all formulas
			for formula in $( ls -1 $REL_FORMULAS_DIR) ; do
				clean "${formula%.*}"
			done
		fi ;;

	dist-clean)

		if [ ! -e $BUILD_DIR ] ; then
			echoInfo " Nothing to clean"
			exit 0
		fi

		# process given libraries
		if [ $# -gt 0 ] ; then
			while [ $# -gt 0 ] ; do
				dist-clean $1
				shift 1
			done

		else # process all formulas
			for formula in $( ls -1 $REL_FORMULAS_DIR) ; do
				dist-clean "${formula%.*}"
			done
		fi ;;

	*)
		echoError " Unknown command \"$A_CMD\""
		exit 1 ;;
esac

exit 0
