name: build-vs

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# env:
#   ccache: ccache

jobs:
  build-vs2022:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, ARM64, ARM64EC]
    env:
      BITS: ${{ matrix.bits }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2.22.0
        with:
          update: true
          install: >-
            git
            unzip
            rsync
            wget2
            wget
      - name: Install dependencies
        shell: msys2 {0}
        run:
          ./scripts/ci/vs/install_bleeding.sh
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build emptyExample
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild examples/templates/emptyExample/emptyExample.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }} /p:PlatformToolset=v143
      - name: Build allAddonsExample
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild examples/templates/allAddonsExample/allAddonsExample.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }} /p:PlatformToolset=v143
      - name: Build DEBUG emptyExample
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild examples/templates/emptyExample/emptyExample.vcxproj /p:configuration=debug /p:platform=${{ matrix.platform }} /p:PlatformToolset=v143
      - name: Build DEBUG allAddonsExample
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild examples/templates/allAddonsExample/allAddonsExample.vcxproj /p:configuration=debug /p:platform=${{ matrix.platform }} /p:PlatformToolset=v143
