name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
    
jobs:

  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        mingw: [MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          unzip
          rsync
          wget
    - name: Install dependencies
      run: ./scripts/ci/msys2/install.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
    - name: Build
      run: ./scripts/ci/msys2/build.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
    - name: Run tests
      run: ./scripts/ci/msys2/run_tests.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
