name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - { sys: mingw64, env: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        update: false
        msystem: ${{matrix.sys.sys}}
        # pacboy: frei0r-plugins freetype libwebp boost assimp gcc gdb glew glfw glm harfbuzz libsndfile libusb libxml2 mpg123 nlohmann-json ntldd-git openal opencv poco pugixml rtaudio tools uriparser utf8cpp zlib
        install: >-
          # git
          # unzip
          # rsync
          # wget
          make
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-libtiff
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-harfbuzz
          mingw-w64-x86_64-opencv
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-frei0r-plugins
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-assimp
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-glew
          mingw-w64-x86_64-glfw
          mingw-w64-x86_64-glm
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-nlohmann-json
          # mingw-w64-x86_64-ntldd-git
          mingw-w64-x86_64-openal
          mingw-w64-x86_64-poco
          mingw-w64-x86_64-pugixml
          mingw-w64-x86_64-rtaudio
          # mingw-w64-x86_64-tools
          mingw-w64-x86_64-uriparser
          mingw-w64-x86_64-utf8cpp
          # mingw-w64-x86_64-zlib
    - name: Install dependencies
      run: ./scripts/ci/msys2/install.sh
    - name: Build
      run: ./scripts/ci/msys2/build.sh
    - name: Run tests
      run: ./scripts/ci/msys2/run_tests.sh
