name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        mingw: [MINGW64,MINGW32]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'open Frameworks'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          unzip
          rsync
          wget
    - name: Install dependencies
      run: |
        cd "${GITHUB_WORKSPACE}/open Frameworks"
        ./scripts/ci/msys2/install.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
    - name: Build
      run: |
        cd "${GITHUB_WORKSPACE}/open Frameworks"
        ./scripts/ci/msys2/build.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
    - name: Run tests
      run: |
        cd "${GITHUB_WORKSPACE}/open Frameworks"
        ./scripts/ci/msys2/run_tests.sh
      env:
        MSYSTEM: ${{ matrix.mingw }}
