name: nightly-linux64

on:
 schedule:
   - cron: "0 6 * * *"
jobs:
  build-linux-platforms:
    runs-on: ubuntu-latest
    if: github.repository == 'openframeworks/openFrameworks' && github.ref == 'refs/heads/master'
    strategy:
        matrix:
          cfg:
          - {target: linux64, libs: 64gcc6}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v3
    - name: Install libunwind
      run:  sudo apt-get install libunwind-dev
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh;
    - name: Download libs
      run: ./scripts/linux/download_libs.sh -a ${{matrix.cfg.libs}};
    - name: Create Package
      run: scripts/ci/package_builds.sh;
      id: createpackage
    - name: Update Release
      uses: IsaacShelton/update-existing-release@v1.3.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        release: nightly
        prerelease: false
        replace: true
        files: ${{ steps.createpackage.outputs.FILES_OUT }}
