name: build-android

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-android:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cfg:
        - {target: android, gradle_target: compileArm7DebugSources}
        - {target: android, gradle_target: compileX86DebugSources}

    env:
      TARGET: ${{matrix.cfg.target}}
      GRADLE_TARGET: ${{matrix.cfg.gradle_target}}
      NDK_DIR: android-ndk-r15c
    steps:
    - uses: actions/checkout@v2
    - name: Cache projectGenerator folder
      uses: actions/cache@v2
      with:
        path: '~/projectGenerator'
        key: ${{ runner.os }}-pg-${{matrix.cfg.gradle_target}}
    - name: Cache NDK
      uses: actions/cache@v2
      with:
        path: '~/android-ndk-r15c'
        key: ${{ runner.os }}-android-ndk-${{matrix.cfg.gradle_target}}
    - name: install
      run: ./scripts/ci/$TARGET/install.sh
    - name: Download libs
      run: ./scripts/$TARGET/download_libs.sh
    - name: Build
      run: ./scripts/ci/$TARGET/build.sh
    - name: Upload Libs
      run: scripts/ci/upload_of_lib.sh;
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
